### ISSUE TITLE
nonebot.adapters.villa.exception.InvalidBotAuthInfo

### ISSUE THREAD

**Issue by Pan-ShiQi** [CMHopeSunshine/nonebot-adapter-villa#34]
### Python 版本

3.10

### 版本

0.6.5

### 描述问题

本地重新搭建环境出现机器人鉴权失败
raise InvalidBotAuthInfo(resp)
nonebot.adapters.villa.exception.InvalidBotAuthInfo: <InvalidBotAuthInfo: 10322005, retcode=10322005, message=机器人鉴权失败, data=None>

### 复现步骤

艾特机器人发送消息出现

**Comment by CMHopeSunshine** [comment]
应该是authkey格式错误，从大别野开放平台复制下来的authkey还需要手动给换行补上换行符`\n`再写到`.env.*`里，即`-----BEGIN PUBLIC KEY-----\nxxxxxxxxxx\nnxxxxxxxxxx\nnxxxxxxxxxx\nnxxxxxxxxxx\nnxxxxxxxxxx\nnxxxxxxxxxx\n-----END PUBLIC KEY-----\n`这种格式，结尾的`\n`也不能缺少。

**Comment by CMHopeSunshine** [comment]
先关了，如还有问题请再反馈
