### ISSUE TITLE
Bug: 机器人未开通 wss

### ISSUE THREAD

**Issue by Agnes4m** [CMHopeSunshine/nonebot-adapter-villa#38]
### Python 版本

3.10.11

### 版本

1.3.4

### 描述问题

ws连接但是显示没有开通，但是在官群问是已经全面开放ws连接，不清楚是bug还是我配置有错误（机器人是未上线，填写的测试频道id是正确的）

### 复现步骤

使用nb2大别野适配器，填写配置，nb run

### 期望的结果

正常启动并可以在大别野交互

## 报错
![image](https://github.com/CMHopeSunshine/nonebot-adapter-villa/assets/70925546/cfe63ca7-d1f1-4096-9d3d-2a3b4e4e0464)
## env配置
![image](https://github.com/CMHopeSunshine/nonebot-adapter-villa/assets/70925546/fdee4f41-5d0c-482d-b5f5-fafc55d687a8)

**Comment by CMHopeSunshine** [comment]
ws测试结束后会默认改回 `http回调`，需在开放平台中将`回调方式`改成 `websocket回调`
